### ISSUE TITLE
Predict

### ISSUE THREAD

**Issue by Virginia9733** [PolarBean/DeepSlice#17]
Hi there,

When I tried the predict() , I got this error:

"DeepSlice.predict('D:\DeepSlice\Brain slices', prop_angles=False)"

Looking forward to hearing from you.

**Comment by Virginia9733** [comment]
Hi there,

When I tried the predict() , I got this error:

"DeepSlice.predict('D:\DeepSlice\Brain slices', prop_angles=False)"

Looking forward to hearing from you.

**Comment by PolarBean** [comment]
Hi! 

That's the command you entered but not the error. though looking at this the issue is you have copied the path directly from windows explorer. the backslashes are escape characters, so i would recommend changing them to forward slashes or placing an 'r' in front of the string (this makes python interpret backslashes as forward slashes). this will always be true when using python, not just for DeepSlice.
