### ISSUE TITLE
Can't align the sections with Allen CCF

### ISSUE THREAD

**Issue by Virginia9733** [PolarBean/DeepSlice#18]
Hi there,

I used serial slices AP from -0.46 to -3.5, 50 ㎛, in total 69 slices as the input of DeepSlice. However, the result is a bit weird.
I checked the XML file in the QuickNII, it shows a huge difference in linear and polinear results, and looks like most of the slices have been mapped to the same ID in Allen CCF. I am not sure what's the issue.

Enclosed with the log file, the output file, samples of slices, and the screenshot of QuickNII.
![69](https://user-images.githubusercontent.com/61534754/181139057-ef17748b-8dc5-4d10-9e70-56d4615673d5.png)

[DeepSlice_CA2CA3EC_Output.csv](https://github.com/PolarBean/DeepSlice/files/9194226/DeepSlice_CA2CA3EC_Output.csv)
![DeepSlice_Output](https://user-images.githubusercontent.com/61534754/181139437-2e3bef47-2a22-4317-89c9-ad1bdae94d3d.png)
![QuickNII-Result-Bad1](https://user-images.githubusercontent.com/61534754/181139170-a0853050-089f-4e40-877b-a5f73fd3a9ae.png)
![QuickNII-Result-Bad](https://user-images.githubusercontent.com/61534754/181139171-fc4fefc3-c297-4aef-9120-0868ce9b648d.png)

[DeepSlice_log.txt](https://github.com/PolarBean/DeepSlice/files/9194228/DeepSlice_log.txt)
![DeepSlice_Log](https://user-images.githubusercontent.com/61534754/181139439-dc5b4519-873b-4485-9649-8f9dbec62cb0.png)

I appreciate any comments or suggestions. Looking forward to hearing from you.

**Comment by PolarBean** [comment]
This indicates that DeepSlice is interpreting all your images as just black. Make sure all your images are 8-bit (as was the issue here https://github.com/PolarBean/DeepSlice/issues/8). If they aren't convert them in imageJ before trying again. I just tried the image you uploaded and it worked find for me (likely as it is a screnshot so is 8-bit :)
![Virginia9733_test](https://user-images.githubusercontent.com/38996929/181212830-a1d83150-f2f9-4b26-9ccc-38855cd842a7.png)
)

**Comment by Virginia9733** [comment]
Hi, thank you so much for your reply!

The image I uploaded is 32-bit PNG, I tried to convert them into 8-bit PNG, 8-bit tiff, 8-bit jpg using ImageJ, still the results look weird. I can't align it with the Allen CCF.

Enclosed with the 8-bit PNG, 8-bit tiff, 8-bit jpg, error message using tiff, output using PNG and JPG, and a screenshot of QuickNII.

Also, interestingly, if I use tiff, I can't save the result, but receive an error message saying: " Invalid filetype: b'MM\x00*\x00\x00\x00\x08\x00\x0c\x00\xfe\x00\x04\x00\x00\x00\x01\x00\x00\x00\x00\x01\x00'"

![OUTPUT](https://user-images.githubusercontent.com/61534754/181522801-675d4515-bdc9-4f11-a8cc-cc6117132e4f.png)
[8 bit png-DeepSlice Log.txt](https://github.com/PolarBean/DeepSlice/files/9210299/8.bit.png-DeepSlice.Log.txt)
![folder structure and 8 dit tiff](https://user-images.githubusercontent.com/61534754/181522814-62bccbbb-1863-463b-b951-68381331b2c5.png)
[can't save result for tiff-invalid file type.txt](https://github.com/PolarBean/DeepSlice/files/9210301/can.t.save.result.for.tiff-invalid.file.type.txt)
[Output-8 bit JPG.csv](https://github.com/PolarBean/DeepSlice/files/9210306/Output-8.bit.JPG.csv)

**Comment by Virginia9733** [comment]
And also, I am using QuickNII-WHSRat-v4 to visualize the result, and I don't know how to show the outline as you did. It only allows me to choose from MRI, DTI or segmentations.

![QuickNII-result1](https://user-images.githubusercontent.com/61534754/181524356-6f98ae62-825d-4c35-8679-c21fc5660e18.png)
![QuickNII-result](https://user-images.githubusercontent.com/61534754/181524360-0bc57946-1486-46da-8320-d9da61d1ec76.png)

**Comment by PolarBean** [comment]
Ah! DeepSlice currently only supports Mouse, though we are working on a rat model and recently presented some preliminary data at FENS it is not ready yet for release. it is still strange that your output looks like this after you converted the images. If you have mouse sections please send me a sample at harry.carey@medisin.uio.no and I will try to determine what is going on. Otherwise the rat will be released in the coming months.

**Comment by PolarBean** [comment]
if you wish to visualise the outline like i did you need to open the QuickNII json in Visualign (our nonlinear adjustment program). https://www.nitrc.org/projects/visualign/

**Comment by PolarBean** [comment]
Dear Muhang, 

thank you for your email. I have identified several issues. 
Firstly since you have mouse sections, you need to use the mouse version of QuickNII (which you select in the drop down menu from here https://www.nitrc.org/projects/quicknii)

Secondly your images must have their section numbers in the name as sXXX where X is the 3 digit section number (ie, s001, s002). 

Furthermore, the implementation of DeepSlice available through DeepSlice.com.au is slightly newer so I would recommend using the web interface most of the time. 

in my tests the 8-bit pngs worked best.

**Comment by Virginia9733** [comment]
THANK YOU SO MUCH for your reply!!!

I have tried it via the web interface, and it works quite well for PNG!
The QuickNII and VisuAlign look
![VisuAlign](https://user-images.githubusercontent.com/61534754/181784415-308ca75f-4838-4a5c-baa1-ebba3deb8472.png)
![QuickNII-segmentation](https://user-images.githubusercontent.com/61534754/181784422-15a390b3-14a4-4e9b-85b4-9b285f20ec0a.png)
![Performance of DeepSlice-QuickNII](https://user-images.githubusercontent.com/61534754/181784424-934b18f0-0704-4ac5-8c01-751ebac4404b.png)
 good as well. I think I need more time to play with those wonderful tools!
Happy Align!!!! Thank you!

**Comment by PolarBean** [comment]
Hey Muhang,
I am happy it works. Don`t forget to try "use section numbers" when using the website as this could improve your accuracy. 
Best of luck
