### ISSUE TITLE
DeepSlice web does not seem to upload images

### ISSUE THREAD

**Issue by ablot** [PolarBean/DeepSlice#25]
Hi @PolarBean 

Thanks again for setting up DeepSlice. I'm not sure if the website is still working. Uploads that were almost instantaneous last year  (a few tens of kb per picture) seem to be stuck forever now. Is there an issue or should I just wait longer?

**Comment by TacticBlack** [comment]
I have had the same issue since around noon (US Eastern Time Zone, GMT +5) and cannot upload my images or the sample images. it just remains on the loading screen. If you click around to figure out what is wrong you eventually get:

AN ERROR HAS OCCURRED
An exception has occurred when retrieving the data for: dbe02ce00f994f9cb9dc67e7f461e695

**Comment by PolarBean** [comment]
yeah. I'll have it back online tomorrow morning Oslo time. Sorry for the inconvenience

**Comment by PolarBean** [comment]
Its back up now!
