### ISSUE TITLE
Cannot pip install DeepsSlice

### ISSUE THREAD

**Issue by Ttan2021** [PolarBean/DeepSlice#47]
Hi, I'm trying to install DeepSlice using pip but am getting this specific error:

"ERROR: Cannot install deepslice==1.0.0, deepslice==1.0.1, deepslice==1.0.11, deepslice==1.0.2, deepslice==1.0.3, deepslice==1.0.4, deepslice==1.0.5, deepslice==1.0.6, deepslice==1.1.0, deepslice==1.1.1, deepslice==1.1.2, deepslice==1.1.3, deepslice==1.1.4, deepslice==1.1.5 and deepslice==1.1.6 because these package versions have conflicting dependencies.

The conflict is caused by:
    deepslice 1.1.6 depends on tensorflow==1.15.0
    deepslice 1.1.5 depends on tensorflow==1.15.0
    deepslice 1.1.4 depends on tensorflow==1.15.0
    deepslice 1.1.3 depends on tensorflow==1.15.0
    deepslice 1.1.2 depends on tensorflow==1.15.0
    deepslice 1.1.1 depends on tensorflow==1.15.0
    deepslice 1.1.0 depends on tensorflow==1.15.0
    deepslice 1.0.11 depends on tensorflow==1.15.0
    deepslice 1.0.6 depends on tensorflow==1.15.0
    deepslice 1.0.5 depends on tensorflow==1.15.0
    deepslice 1.0.4 depends on tensorflow==1.15.0
    deepslice 1.0.3 depends on tensorflow==1.15.0
    deepslice 1.0.2 depends on tensorflow==1.15.0
    deepslice 1.0.1 depends on tensorflow==1.15.0
    deepslice 1.0.0 depends on tensorflow==1.15.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts"

Has anyone ran into this error and what have you done to get around this issue?

Thanks!

**Comment by Ttan2021** [comment]
Also I tried looking for tensorflow 1.15 but could only find a stackoverflow thread which did not work for me unfortunately.

**Comment by PolarBean** [comment]
Do you have an environment with python 3.7 installed? this might be due to that :)

**Comment by PolarBean** [comment]
This should no longer be a problem, as DeepSlice works with newer python versions now

**Comment by jcs-01** [comment]
I'm still having this issue. 
I'm running pip 24.0 and python 3.12.3 and getting the same error message as above (I'll paste it in here if that's helpful too). Do you have any suggestions about what to try? I'm using the pip install DeepSlice command.



ERROR: Cannot install deepslice==1.0.0, deepslice==1.0.1, deepslice==1.0.11, deepslice==1.0.2, deepslice==1.0.3, deepslice==1.0.4, deepslice==1.0.5, deepslice==1.0.6, deepslice==1.1.0, deepslice==1.1.1, deepslice==1.1.2, deepslice==1.1.3, deepslice==1.1.4, deepslice==1.1.5, deepslice==1.1.6, deepslice==1.1.7, deepslice==1.2, deepslice==1.2.1, deepslice==1.2.2 and deepslice==1.2.3 because these package versions have conflicting dependencies.

The conflict is caused by:
    deepslice 1.2.3 depends on tensorflow<=2.15.0
    deepslice 1.2.2 depends on tensorflow<=2.15.0
    deepslice 1.2.1 depends on tensorflow<=2.15.0
    deepslice 1.2 depends on tensorflow<=2.15.0
    deepslice 1.1.7 depends on tensorflow==1.15.0
    deepslice 1.1.6 depends on tensorflow==1.15.0
    deepslice 1.1.5 depends on tensorflow==1.15.0
    deepslice 1.1.4 depends on tensorflow==1.15.0
    deepslice 1.1.3 depends on tensorflow==1.15.0
    deepslice 1.1.2 depends on tensorflow==1.15.0
    deepslice 1.1.1 depends on tensorflow==1.15.0
    deepslice 1.1.0 depends on tensorflow==1.15.0
    deepslice 1.0.11 depends on tensorflow==1.15.0
    deepslice 1.0.6 depends on tensorflow==1.15.0
    deepslice 1.0.5 depends on tensorflow==1.15.0
    deepslice 1.0.4 depends on tensorflow==1.15.0
    deepslice 1.0.3 depends on tensorflow==1.15.0
    deepslice 1.0.2 depends on tensorflow==1.15.0
    deepslice 1.0.1 depends on tensorflow==1.15.0
    deepslice 1.0.0 depends on tensorflow==1.15.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by PolarBean** [comment]
ok I havent tested with python 3.12, could you try with 3.11?

**Comment by jcs-01** [comment]
That works! Thank you!
