### ISSUE TITLE
DS-GPU.yml file not included in conda_environments

### ISSUE THREAD

**Issue by TacticBlack** [PolarBean/DeepSlice#7]
Title says it all. File "DS-GPU.yml" does not appear in repo.

**Comment by PolarBean** [comment]
Thanks for the heads up! I'll fix this tomorrow.

**Comment by thecobb** [comment]
Just wanted to check if the DS-GPU.yml was still going to be added? While I was able to configure a local conda environment that is able to run Deepslice and utilizes the GPU (using Tensorflow 1.15 since I took some hints from the example collab notebook which I downloaded and modified to test my installation with the example_brain), I'd like to install this on another workstation and having the DS-GPU.yml file would make that easier.
